version: '3.7'
services:
    offlineimap_personal:
        build: ./offlineimap/
        restart: always
        volumes:
            - ../maildir:/var/mail/maildir
            - ../secrets:/var/mail/secrets
            - ./offlineimap.conf:/var/mail/.offlineimaprc
        command: offlineimap -a personal
    offlineimap_qut:
        build: ./offlineimap/
        restart: always
        volumes:
            - ../maildir:/var/mail/maildir
            - ../secrets:/var/mail/secrets
            - ./offlineimap.conf:/var/mail/.offlineimaprc
        command: offlineimap -a qut
    offlineimap_student:
        build: ./offlineimap/
        restart: always
        volumes:
            - ../maildir:/var/mail/maildir
            - ../secrets:/var/mail/secrets
            - ./offlineimap.conf:/var/mail/.offlineimaprc
        command: offlineimap -a student
    notmuch:
        build: ./notmuch/
        restart: always
        volumes:
            - ../maildir:/var/mail/maildir
            - ../.ssh/authorized_keys:/tmp/.ssh/authorized_keys
            - ./notmuch.conf:/var/mail/.notmuch-config
        ports:
            - "47474:22"

      
