version: '3.7'
services:
    offlineimap:
        build: ./offlineimap/
        volumes:
            - ~/maildir:/var/mail/maildir
            - ~/secrets:/var/mail/secrets
            - ./offlineimap.conf:/var/mail/.offlineimaprc
        restart: always
    notmuch:
        build: ./notmuch/
        volumes:
            - ~/maildir:/var/mail/maildir
            - ~/.ssh/authorized_keys:/tmp/.ssh/authorized_keys
            - ./notmuch.conf:/var/mail/.notmuch-config
        ports:
            - "47474:22"
        restart: always

      
